### ISSUE TITLE
RMarkdown misses support for html notebooks

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3317]
Enhance html view to also look for derived `*.nb.html` files.

Test yaml:

```
---
title: "Generate an html notebook"
author: "cocalc"
output:
  html_notebook:
    toc: yes
---

## Let's test
```
