### ISSUE TITLE
compute server: redo the kubernetes image using k3s instead of microk8s

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#8293]
For our purposes k3s is MUCH better than microk8s.  

It's very easy to scale up, faster to install, etc.

Regarding a "hello world":

1. Install k3s as root (on bare VM, outside Docker, obviously): `curl -sfL https://get.k3s.io | sh -`
2. Install [hello world](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/) web server: `kubectl create deployment web --image=gcr.io/google-samples/hello-app:1.0` 
3. Expose it: `kubectl expose web`
4. Define this Ingress file and do `kubectl apply -f ingress.yaml`:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web

spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
```
Port 80 on localhost (etc) will now be the hello world web server.

5. Change the proxy config for the compute server to be
```json
[{ "path": "/", "target": "http://localhost", options:{}, wsOptions:{}}]
```

6: Now it works, e.g.,

<img width="492" alt="Image" src="https://github.com/user-attachments/assets/2342bd15-1bf3-4a83-8ff9-d0d9147327ae" />
